name: ci build and bush docker image to ECR
on:
  push:
    branches:
      - main
  
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 744531146604.dkr.ecr.us-east-1.amazonaws.com
      
      - name: Build and push image to Amazon ECR
        run: |
            IMAGE_TAG=${{ github.run_number }}
            docker build -t mediplus:${IMAGE_TAG} .
            docker tag mediplus:${IMAGE_TAG} 744531146604.dkr.ecr.us-east-1.amazonaws.com/mediplus:${IMAGE_TAG}
            docker push 744531146604.dkr.ecr.us-east-1.amazonaws.com/mediplus:${IMAGE_TAG}
            
      - name: trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 744531146604.dkr.ecr.us-east-1.amazonaws.com/mediplus:${{ github.run_number }}
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          cache-dir: /tmp/.trivycache
          scan-type: 'image'
          timeout: '5m'

  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: check my ssh key
        run: |
          echo "${{secrets.SSH_KEY}}" > ssh_key.pem
          chmod 600 ssh_key.pem
          cat ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@34.224.7.110 "docker pull 744531146604.dkr.ecr.us-east-1.amazonaws.com/mediplus:v2"
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@34.224.7.110 "docker rm -f mediplus || true"
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@34.224.7.110 "docker run -d --name mediplus -p 80:80 744531146604.dkr.ecr.us-east-1.amazonaws.com/mediplus:v2"
      
      
